---
title: "{{TITLE}}"
subtitle: "{{DESCRIPTION}}"
date: "Last built: `r Sys.time()`"
params:
    hashtag: "{{HASHTAG}}"
    # Times
    start_day: "{{START_DAY}}"
    end_day: "{{END_DAY}}"
    timezone: "{{TIMEZONE}}"
    # Plot theme and colours
    theme: "{{THEME}}"
    accent: "{{ACCENT}}"
    accent2: "{{ACCENT2}}"
    # Analysis parameters
    kcore: {{KCORE}}
    topics_k: {{TOPICS}}
    bigram_filter: {{BIGRAM}}
    # Dataset fixed, set true to stop adding new tweets
    fixed: {{FIXED}}
    # Random seed
    seed: {{SEED}}
---

```{r knitr, include = FALSE}
DOCNAME <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.path       = paste0("figures/", DOCNAME, "/"),
    fig.width      = 10,
    fig.height     = 8,
    message        = FALSE,
    warning        = FALSE
)
```

```{r libraries, include = FALSE}
source(here("R", "libraries.R"))
```

**Parameters**

```{r params}
params_table <- data.frame(Parameter = names(params), Value = unlist(params))

kable(params_table, row.names = FALSE)
```

```{r load}
data_file <- here("data", paste0(DOCNAME, ".Rds"))
hashtags_vec <- str_split(params$hashtag, ",")[[1]]
hashtags_query <- paste(hashtags_vec, collapse = " OR ")

if (params$fixed) {
    if (file_exists(data_file)) {
        tweets <- readRDS(data_file)
    } else {
        stop("fixed is TRUE but no data file exists", call. = FALSE)
    }
} else {
    if (file_exists(data_file)) {
        existing_tweets <- readRDS(data_file)
        message(nrow(existing_tweets), " tweets already downloaded")
        
        new_tweets <- search_tweets(hashtags_query, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(new_tweets), " tweets")
        
        tweets <- new_tweets %>%
            rbind(existing_tweets) %>%
            group_by(status_id) %>%
            top_n(1, collected_at) %>%
            ungroup()
        message("Dataset now contains ", nrow(tweets), " tweets")
    } else {
        tweets <- search_tweets(hashtags_query, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(tweets), " tweets")
    }
    saveRDS(tweets, data_file)
}

tweets <- tweets %>%
    mutate(
        date     = as_date(created_at, tz = params$timezone),
        datetime = as_datetime(created_at, tz = params$timezone),
        hour     = hour(datetime)
    )
```

# Introduction

An analysis of tweets for the query `r hashtags_query` related to
{{DESCRIPTION}} from `r params$start_day` to `r params$end_day`. A total of
`r nrow(tweets)` tweets from `r  length(unique(tweets$screen_name))` users were
collected using the **{rtweet}** R package.

```{r analysis, child = "_analysis.Rmd"}
# This chunk adds the template analysis
```

# Session info {.unnumbered}

```{r session-info}
sessionInfo()
```
